### ISSUE TITLE
Specification for EXMARaLDA import?

### ISSUE THREAD

**Issue by berndmoos** [hexatomic/hexatomic#441]
**Is your feature request related to a problem? Please describe.**
I would like to understand how to import EXMARaLDA files into Hexatomic. Right now, my naive attempts (with a transcription from the EXMARaLDA demo-corpus) fail with error messages of the following kind in the log:

```
08:18:25.732 [EXMARaLDAImporter_mapper(salt:/EXMARaLDA_DemoKorpus_EN/StructureErrors)] ERROR MyImporter - An exception was thrown by the mapper threads 'Thread[EXMARaLDAImporter_mapper(salt:/EXMARaLDA_DemoKorpus_EN/StructureErrors),5,EXMARaLDAImporter_mapperGroup]'.
org.corpus_tools.pepper.modules.exceptions.PepperModuleDataException: A data error occured for a Pepper mapper 'org.corpus_tools.peppermodules.exmaralda.EXMARaLDA2SaltMapper'. Cannot convert given exmaralda file 'file:/C:/Users/bernd/OneDrive/Desktop/EXMARaLDA_DemoKorpus_EN/StructureErrors.xml', because no textual source layer was found.
        at org.corpus_tools.peppermodules.exmaralda.EXMARaLDA2SaltMapper.mapSDocument(EXMARaLDA2SaltMapper.java:217)
        at org.corpus_tools.pepper.impl.PepperMapperControllerImpl.map(PepperMapperControllerImpl.java:251)
        at org.corpus_tools.pepper.impl.PepperMapperControllerImpl.run(PepperMapperControllerImpl.java:188)
08:18:26.540 [ModalContext] ERROR o.c.h.f.i.ImportWizard - Error(s) during import: Corpus was not imported due to errors. Please check the log messages for any issues and make sure you have selected the correct format.
```

```
08:21:32.141 [EXMARaLDAImporter_mapper(salt:/PaulMcCartney/PaulMcCartney)] ERROR MyImporter - Cannot map 'salt:/0/PaulMcCartney/PaulMcCartney' with module 'EXMARaLDAImporter', because of a mapping result was 'FAILED'.
08:21:32.142 [EXMARaLDAImporter_mapper(salt:/PaulMcCartney/PaulMcCartney)] ERROR MyImporter - An exception was thrown by the mapper threads 'Thread[EXMARaLDAImporter_mapper(salt:/PaulMcCartney/PaulMcCartney),5,EXMARaLDAImporter_mapperGroup]'.
org.corpus_tools.pepper.modules.exceptions.PepperModuleException: Any exception occured while mapping.
        at org.corpus_tools.pepper.impl.PepperMapperControllerImpl.run(PepperMapperControllerImpl.java:193)
Caused by: org.corpus_tools.salt.exceptions.SaltException: Cannot set the name of this label object, because it is empty.
        at org.corpus_tools.salt.graph.impl.LabelImpl.setName(LabelImpl.java:96)
        at org.corpus_tools.hexatomic.core.events.salt.LabelNotifierImpl.lambda$4(LabelNotifierImpl.java:84)
        at org.corpus_tools.hexatomic.core.events.salt.LabelNotifierImpl.modified(LabelNotifierImpl.java:112)
        at org.corpus_tools.hexatomic.core.events.salt.LabelNotifierImpl.setName(LabelNotifierImpl.java:84)
        at org.corpus_tools.salt.graph.impl.LabelImpl.setName(LabelImpl.java:92)
        at org.corpus_tools.peppermodules.exmaralda.EXMARaLDA2SaltMapper.mapUDInformations2SAnnotationContainer(EXMARaLDA2SaltMapper.java:472)
        at org.corpus_tools.peppermodules.exmaralda.EXMARaLDA2SaltMapper.mapMetaInformation2SDocument(EXMARaLDA2SaltMapper.java:372)
        at org.corpus_tools.peppermodules.exmaralda.EXMARaLDA2SaltMapper.mapSDocument(EXMARaLDA2SaltMapper.java:172)
        at org.corpus_tools.pepper.impl.PepperMapperControllerImpl.map(PepperMapperControllerImpl.java:251)
        at org.corpus_tools.pepper.impl.PepperMapperControllerImpl.run(PepperMapperControllerImpl.java:188)
08:21:33.118 [ModalContext] ERROR o.c.h.f.i.ImportWizard - Error(s) during import: Corpus was not imported due to errors. Please check the log messages for any issues and make sure you have selected the correct format.
```
The first message seems to be caused because the importer is also attempting to read a "*.xml" file which is not an EXMARaLDA transcription. The second message, I cannot interpret. 

**Describe the solution you'd like**
I would like a specification of what properties an EXB file should have and how the folder structure of the corpus should be organised so that it can be imported into Hexatomic.

**Describe alternatives you've considered**
Not importing it ;-)

**Additional context**

**Get credited**
@berndmoos

**Comment by thomaskrause** [comment]
We rely on the Pepper importer for importing the EXMARaLDA files, and it tries to be very inclusive about the files it wants to import, but unfortunately only relies on the file endings.

It will import all files with the ending  "exb", "xml", "xmi" and "exmaralda" in a folder and its subfolders. The top level folder will be used a corpus name, each sub-folder will be a sub-corpus.

```
EXMARaLDA_DemoKorpus_EN/
 + A.exb
 + B.exb
 + subcorpus1/
    + D.exb
    + E.exb
```

I added an issue about this in the importer itself: https://github.com/korpling/pepperModules-EXMARaLDAModules/issues/15
We should be able to make this an option in Hexatomic in the importer UI as well.
